/* SPDX-License-Identifier: Apache-2.0 */
/*
 * YukiZygisk - Reproducible offline WebUI dependency assets.
 *
 * License: Apache-2.0
 *
 * Author: Anatdx
 */

import { build } from 'esbuild';
import { XMLBuilder, XMLParser } from 'fast-xml-parser';
import { copyFile, mkdir, readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const directory = path.dirname(fileURLToPath(import.meta.url));
const dependencies = path.join(directory, 'node_modules');
const assets = path.resolve(directory, '../../webui/assets');

const icons = [
  'activity', 'layers', 'settings-2', 'info', 'refresh-cw', 'adb',
  'check', 'x', 'chevron-right', 'chevron-down', 'external-link', 'cpu',
  'smartphone', 'shield-check', 'shield-alert', 'circle-alert', 'circle-check',
  'moon', 'sun', 'monitor', 'languages', 'terminal', 'boxes', 'memory-stick',
  'logs', 'link', 'search', 'arrow-left', 'ellipsis-vertical', 'loader-circle',
];

await mkdir(assets, { recursive: true });
await build({
  entryPoints: [path.join(directory, 'components.js')],
  outfile: path.join(assets, 'material.js'),
  bundle: true,
  format: 'esm',
  target: 'es2020',
  // Escape whitespace inside generated strings instead of emitting literal
  // trailing tabs from Lit's template parser regular expressions.
  supported: { 'template-literal': false },
  minify: true,
  legalComments: 'eof',
  banner: {
    js: '/* SPDX-License-Identifier: Apache-2.0 AND BSD-3-Clause AND 0BSD */\n/* Material Web 2.5.0 and Lit. Upstream licenses: LICENSE.material, LICENSE.lit, LICENSE.tslib. Generated by tools/webui/build.mjs. */',
  },
});

const parser = new XMLParser({ ignoreAttributes: false, preserveOrder: true });
const builder = new XMLBuilder({ ignoreAttributes: false, preserveOrder: true });
const symbols = [];
for (const name of icons) {
  const filename = name === 'adb' ? path.join(directory, 'icons/adb.svg')
    : path.join(dependencies, 'lucide-static/icons', `${name}.svg`);
  const document = parser.parse(await readFile(filename, 'utf8'));
  const svg = document.find((element) => element.svg);
  if (!svg || !svg[':@']?.['@_viewBox'])
    throw new Error(`Missing SVG viewBox for ${name}`);
  const attributes = { ...svg[':@'], '@_id': name };
  delete attributes['@_xmlns'];
  delete attributes['@_width'];
  delete attributes['@_height'];
  symbols.push({ symbol: svg.svg, ':@': attributes });
}
const sprite = builder.build([
  { svg: symbols, ':@': { '@_xmlns': 'http://www.w3.org/2000/svg' } },
]);
await writeFile(path.join(assets, 'icons.svg'),
  '<!-- SPDX-License-Identifier: ISC AND MIT AND Apache-2.0 -->\n<!-- Lucide 1.49.0 icons. Original licenses: LICENSE.lucide. -->\n<!-- Material Adb icon. Copyright 2025 The Android Open Source Project. Apache-2.0: LICENSE.material. Source: tools/webui/icons/adb.svg. -->\n<!-- Generated by tools/webui/build.mjs. -->\n' + sprite + '\n');

await copyFile(path.join(dependencies, '@material/web/LICENSE'),
  path.join(assets, 'LICENSE.material'));
await copyFile(path.join(dependencies, 'lucide-static/LICENSE'),
  path.join(assets, 'LICENSE.lucide'));
await copyFile(path.join(dependencies, 'tslib/LICENSE.txt'),
  path.join(assets, 'LICENSE.tslib'));

const litPackages = [
  'lit', 'lit-element', 'lit-html', '@lit/reactive-element', '@lit/context',
];
const litNotices = [];
for (const name of litPackages) {
  const root = path.join(dependencies, name);
  const manifest = JSON.parse(await readFile(path.join(root, 'package.json'), 'utf8'));
  const license = await readFile(path.join(root, 'LICENSE'), 'utf8');
  litNotices.push(`${name} ${manifest.version}\n\n${license.trim()}\n`);
}
await writeFile(path.join(assets, 'LICENSE.lit'), litNotices.join('\n\n'));

console.log(`Built local Material Web components and ${icons.length} WebUI symbols.`);
